### ISSUE TITLE
Multiple timelines do not work in boostrap accordion

### ISSUE THREAD

**Issue by janvodopivec** [squarechip/timeline#11]
Hey, i found a problem. If i put multiple timelines in bootstrap accordion  only 1 timeline get displayed. 

If multiple  timelines are added in modal directly it works but when i add them into accordion only first one gets displayed rest dont load. 

Any idea why?

Thank you.

**Comment by squarechip** [comment]
I assume this is the same as #12 which is resolved. So I'll close this issue.
