### ISSUE TITLE
Multiple timelines not working in Bootstrap Modal Accordion

### ISSUE THREAD

**Issue by janvodopivec** [squarechip/timeline#12]
Hello,

i just tried to you this plugin to display multiple timeline in 1 modal, if i only display timelines it works, but when i put those timeline in Accordion to make UI more user friendly, only first timeline is properly displayed rest are not. The HTML elements are still there and can be found with inspector but they are not displayed correctly.

Any idea how to fix this or what might be the problem?

Thank you.

**Comment by squarechip** [comment]
Hi. This sounds similar to issue #3 
You may need to initialise the timeline once the modal is visible.

Let me know if this helps.

Thanks.

**Comment by janvodopivec** [comment]
Hello,

followed your advice and got it working, as you suspected it was a #3 related issue with elemnt widths 

Got ti working with the folowing code
```
$('#accordion').on('shown.bs.collapse', function () {
    timeline(document.querySelectorAll('.timeline'), {
        mode: 'horizontal'
    });
});
```
Thank you.

**Comment by squarechip** [comment]
Cool. Glad it's working now. I'll mark as closed.
