### ISSUE TITLE
No rendering with less than three items

### ISSUE THREAD

**Issue by OliverGrohme** [squarechip/timeline#20]
I want to use the script to visualize the process of an approval. But with less than 3 elements the script has problems displaying the timeline. Nothing is displayed.
Update: Happens only in horizontal mode

**Comment by squarechip** [comment]
If you could post the code you are using somewhere, I would be happy to have a look as I can't seem to recreate this. Thanks!

**Comment by OliverGrohme** [comment]
I could fix the problem by setting the visibleItems parameter to less than 3.
