### ISSUE TITLE
Define Startpoint (Reverse)

### ISSUE THREAD

**Issue by barbiscp** [squarechip/timeline#4]
Hello,

thank you for you great timeline!
I would like to have the view port starting from the middle of my timeline content. 
So the navigation arrows will be both enabled just from beginning, not just the right one.
Is that possible?

Thank you & Best regards

**Comment by MuratAmca** [comment]
Hello,
This is also what I need to :)
Because some of the items belong to past and some of them to future. If I can set a start item (maybe in settings) it would be great.

Very best,
Murat

**Comment by MuratAmca** [comment]
I added a setting "startIndex" (default value:0) and changed variable **o** value:

`    function(e) {
     o = 0, e.timelineEl.classList.remove("timeline--horizontal", "timeline--mobile"), e.scroller.removeAttribute("style"), e.items.forEach(function(e) {
      e.removeAttribute("style"), e.classList.remove("animated", "fadeIn", "timeline__item--left", "timeline__item--right");
     });
`

to 

`    function(e) {
     o = e.settings.startIndex, e.timelineEl.classList.remove("timeline--horizontal", "timeline--mobile"), e.scroller.removeAttribute("style"), e.items.forEach(function(e) {
      e.removeAttribute("style"), e.classList.remove("animated", "fadeIn", "timeline__item--left", "timeline__item--right");
     });
`

_o = e.settings.startIndex_

That's it.

**Comment by barbiscp** [comment]
Hello Murat,

thank you for your effort.

Can you provide the full code with the new feature?

Best Regards

**Comment by squarechip** [comment]
Hi, 

Sorry I have been busy so haven't had a chance to look at this, but I will release an updated version with a start index setting over the weekend if that helps.

Thanks.

**Comment by squarechip** [comment]
This has been added. You can define a start point in the configuration settings using 'startIndex' or using the data attribute 'data-start-index'.

**Comment by MuratAmca** [comment]
Thank you Mike :)
