### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetLeft' of undefined

### ISSUE THREAD

**Issue by felipesmendes** [squarechip/timeline#5]
Hello,

I'm trying to use the plugin and was follow the instructions, then I got this error when try to use the plugin in horizontal mode.

```
Uncaught TypeError: Cannot read property 'offsetLeft' of undefined
    at c (timeline.js:291)
    at r (timeline.js:329)
    at timeline.js:391
    at Array.forEach (<anonymous>)
    at s (timeline.js:381)
    at timeline (timeline.js:403)
    at HTMLDocument.<anonymous> (controle-jornada:25)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
```

**Comment by squarechip** [comment]
Hi,

Could you do a JSFiddle with your code or paste it here so that I can take a look please, as I can't seem to recreate the issue.

**Comment by squarechip** [comment]
Marking as closed as I haven't heard back in 10 days and it looks like a set up issue. Let me know if you haven't sorted it though and you have your code available so that I can take a look.

**Comment by alkinbg** [comment]
https://jsfiddle.net/alkinbg/e0co2fab/3/ 
The error only appears if we have less than three timeline__items.

**Comment by ghost** [comment]
Hi @squarechip , i like this plugin. Any solutions to this thanks
![image](https://github.com/squarechip/timeline/assets/142130522/6ce7d70f-403d-4f94-b1f4-d7f38a14a9d3)

![image](https://github.com/squarechip/timeline/assets/142130522/fc2eeaee-cd2e-4923-87b9-94d0e2b4c3d2)

It is happening data-mode="horizontal" with data-move-items="1" data-visible-items="3" with total of 4 items

IF YOU ADD data-start-index="0" above, the offset Error will show on FIRST CLICK of next button

Anyways, I already **solved** this by doing the conditon below:

If data-start-index="0", Do not use data-start-index Attribute Else if the data index is 1 and above then you can use  Attribute  data-start-index

Thanks
