### ISSUE TITLE
Visible Items issue

### ISSUE THREAD

**Issue by mikex0101** [squarechip/timeline#9]
Hi, I'm using the horizontal timeline with a mysql database feeding the events into a php template . If I set the visible items to 6 and there are only 4 events so far, the timeline doesn't show. Could there be a fix for this where the visible items is a maximum and not a minimum number?
Thanks,
Mike

**Comment by squarechip** [comment]
I have tested this and it does seem to work no matter how many items you add in comparison to the 'visibleItems' prop. It just won't show arrows if there are not enough items to scroll left or right, but this is the correct plugin functionality.
